on:
  push:

jobs:
  build-client:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: NPM cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('client/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
        working-directory: client
      - name: Run build
        run: npm run build
        working-directory: client

  deploy-server:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - build-client
    steps:
      - uses: actions/checkout@v2
      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: ${{ secrets.DETA_NAME }}
          deta-project: ${{ secrets.DETA_PROJECT }}
          deta-project-dir: server

  deploy-client:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - build-client
    name: Deploy to docker
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: client
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/under-construction-counter:latest
